### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms#18]
```
brew install gcc
brew install openblas
brew install fftw
export CC=gcc-8 && make

export OMP_NUM_THREADS=4
export VECLIB_MAXIMUM_THREADS=4
```

**Comment by MikaelSlevinsky** [comment]
I have to learn how to write `configure` files. Should the build script install dependencies? Also, I believe the library builds on OS X's gcc-4.2.1 provided OpenMP support is not requested. And I think it works with a relatively low version of gcc on linux.

**Comment by dlfivefifty** [comment]
You don't "have" to do anything. Find peace in your current knowledge of configure files. Only then can you ascend to the next level of configure file writing.

**Comment by dlfivefifty** [comment]
How do I increase the number of threads?

PS Works great for numerical differentiation when combined with MultivariateOrthogonalPolynomials.jl!

**Comment by MikaelSlevinsky** [comment]
Threads are controlled by environment variables OMP_NUM_THREADS, VECLIB_MAXIMUM_THREADS.

Cheers,

Mikael

On Aug 18, 2018, at 5:36 AM, Sheehan Olver <notifications@github.com<mailto:notifications@github.com>> wrote:


How do I increase the number of threads?

PS Works great for numerical differentiation when combined with MultivariateOrthogonalPolynomials.jl!

**Comment by dlfivefifty** [comment]
Hmm, any idea why I'm only getting one thread?
```julia
julia> using ApproxFun, MultivariateOrthogonalPolynomials

julia> @time f = Fun((x,y) -> cos(5000x*y), Triangle(), 4_000_000);
 27.077717 seconds (164.02 M allocations: 8.852 GiB, 5.20% gc time)
```

**Comment by MikaelSlevinsky** [comment]
Perhaps try isolating whether the library itself built with multithreading or whether it's the use in Julia? (Did 0.7's ccall API change such that `JULIA_NUM_THREADS` dictates the overall thread usage?)
In the repository, run `./test_drivers 1 7` with the Activity Monitor running. For degrees `N>1000`, the multithreading should be apparent.

There's a separate issue of further optimizing the triangle transforms by fusing the independent Jacobi parameter conversions in the pre-computation. (This is explains why particular values of alpha, beta, and gamma are significantly faster.)

**Comment by dlfivefifty** [comment]
Can we have the # of threads be passed in as. a variable to the function?

**Comment by dlfivefifty** [comment]
I don't know what that means. tell me what to type and I'll try it

**Comment by MikaelSlevinsky** [comment]
Something like `ft_set_threads(n::Int) = ccall((:omp_set_num_threads, libfasttransforms), Nothing, (Int, ), n)`? I don't have my work computer so can't confirm.

**Comment by dlfivefifty** [comment]
Wow, this is embarrassing: it looked like it was single threaded because all the time was taken constructing the `points`...

**Comment by MikaelSlevinsky** [comment]
Have you seen this repos? [FastPaduaPoints.jl](https://imgflip.com/i/2gqgx7)

**Comment by dlfivefifty** [comment]
Why does Github not have a middle finger reaction?

That wasn't the slow bit. The slow bit was mapping from the rectangle `[-1,1]^2` to the rectangle `[0,1]^2`...
