### ISSUE TITLE
Make not working on Mojave

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms#26]
```julia
[solver-mbook:~/Projects/FastTransforms] solver% export CC=gcc-8 && make
make lib
gcc-8 -Ofast  -march=native -mtune=native -I./src -I/usr/local/opt/openblas/include -I/usr/local/opt/fftw/include -shared -lm -fPIC -fopenmp src/transforms.c src/rotations.c src/permute.c src/drivers.c src/fftw.c -L/usr/local/opt/openblas/lib -L/usr/local/opt/fftw/lib -lm -lblas -lfftw3 -lfftw3_threads -o libfasttransforms.dylib
In file included from src/transforms.c:3:
src/ftinternal.h:4:10: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
          ^~~~~~~~~~
compilation terminated.
In file included from /usr/local/opt/openblas/include/openblas_config.h:104,
                 from /usr/local/opt/openblas/include/cblas.h:5,
                 from src/fasttransforms.h:4,
                 from src/rotations.c:3:
/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
 #include <_stdio.h>
          ^~~~~~~~~~
compilation terminated.
In file included from src/permute.c:3:
src/ftinternal.h:4:10: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
          ^~~~~~~~~~
compilation terminated.
In file included from /usr/local/opt/openblas/include/openblas_config.h:104,
                 from /usr/local/opt/openblas/include/cblas.h:5,
                 from src/fasttransforms.h:4,
                 from src/drivers.c:3:
/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
 #include <_stdio.h>
          ^~~~~~~~~~
compilation terminated.
In file included from /usr/local/opt/openblas/include/openblas_config.h:104,
                 from /usr/local/opt/openblas/include/cblas.h:5,
                 from src/fasttransforms.h:4,
                 from src/fftw.c:3:
/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
 #include <_stdio.h>
          ^~~~~~~~~~
compilation terminated.
make[1]: *** [lib] Error 1
make: *** [all] Error 2
```

**Comment by MikaelSlevinsky** [comment]
This is the same compilation error that used to appear in Travis' macOS builds, even on High Sierra.

I fixed it via https://github.com/MikaelSlevinsky/FastTransforms/commit/f623ae8ef7323883ff5b2bbc094a476b9fad34aa, which I found from some other GitHub repository feeling the same effects.

I've never experienced this error on either of my macs, but look forward to it!

**Comment by MikaelSlevinsky** [comment]
Also, the default `FT_FFTW_FLAGS` is now `FFTW_MEASURE`, but this may be an unduly burdensome for live computations. (I think FFTW stores some of the microkernels it compares, so perhaps the overhead is just experienced the first time at fixed degree).

**Comment by dlfivefifty** [comment]
The FFT time is non-negligible, right? Why not use MKL which is apparently much faster?

**Comment by MikaelSlevinsky** [comment]
Could be used, but would require some modifications since MKL is incomplete. In particular, it doesn't implement real-to-complex transforms with split storage, halfcomplex-to-real transforms, or multidimensional real-to-real transforms. https://software.intel.com/en-us/mkl-developer-reference-c-using-fftw3-wrappers

**Comment by MikaelSlevinsky** [comment]
BTW, I added a proposal for Julia wrapper here https://github.com/MikaelSlevinsky/FastTransforms.jl/commit/ee98f4041e8bd8e6bf4079176eb776cb00728bd5

**Comment by dlfivefifty** [comment]
Fixed it!! Here's the instructions

1. Run (from https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave)
```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```
to restore `/usr/include` and `/usr/lib`

2. Add 
```
CFLAGS += -I/usr/include
LDFLAGS += -L/usr/lib
```
to Make.inc

**Comment by MikaelSlevinsky** [comment]
Is 2. necessary? are they not default search paths for gcc (which is why it can't find the headers to begin with)?

**Comment by dlfivefifty** [comment]
Probably: I tried without them.

**Comment by MikaelSlevinsky** [comment]
This is some next-level gatekeeping from Apple

**Comment by MikaelSlevinsky** [comment]
Fun fact that I've been experimenting with recently: you can compile one file into assembly using one compiler (gcc-8 on rotations.c => rotations.s) and then use a different compiler to turn the assembly into executables/libraries. Clang has significantly better control over OpenMP threads, which is pronounced for low degrees.

**Comment by dlfivefifty** [comment]
Actually, I just needed to rebuild gcc (I deleted /usr/local and started from scratch with homebrew)
