### ISSUE TITLE
Generalised Zernike polynomials?

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms#51]
I remember there used to be docs on what the transforms actually do, but they seem to have disappeared from the docs page! Where's the Disk transform definition, for example??

**Comment by MikaelSlevinsky** [comment]
The doxygen layout is kinda strange in that any added pages are under the "Related Page" tab, so is this what you were remembering? https://mikaelslevinsky.github.io/FastTransforms/transforms.html

**Comment by dlfivefifty** [comment]
Thanks!! @tsgut here's the link

We actually want to do generalised Zernike polynomials. That is, orthogonal w.r.t. (1-r^2)^β. Is that possible?

**Comment by MikaelSlevinsky** [comment]
These are spin-weighted Zernike? or different?

**Comment by dlfivefifty** [comment]
Don't think so...

**Comment by dlfivefifty** [comment]
They are just like Zernike but with `β` in the Jacobi paramters somewhere

**Comment by MikaelSlevinsky** [comment]
It should be possible to support orthonormality with respect to r^a (1-r^2)^b on the disk.

**Comment by MikaelSlevinsky** [comment]
A pull request will soon appear for generalized Zernike polynomials, orthonormal w.r.t L^2(D^2, r^{2α+1}(1-r^2)^β dr dθ).
