### ISSUE TITLE
Vectorized transforms with non-power-of-two degrees

### ISSUE THREAD

**Issue by MikaelSlevinsky** [MikaelSlevinsky/FastTransforms#6]
This has been done for

- [x] spherical harmonics
- [x] triangular harmonics
- [x] disk harmonics
- [x] spin-weighted spherical harmonics

**Comment by dawese** [comment]
Works for disk harmonics now too. Will continue with triangular next.

**Comment by MikaelSlevinsky** [comment]
P.S. spin-weighted are forthcoming!

**Comment by dawese** [comment]
Current vectorization for spin weighted (SSE and AVX) can use non powers of two. Thought that would be useful while AVX512 is forthcoming.

**Comment by dawese** [comment]
Spin weighted is now finished. This completes the issue.
